jwt:
  expiration-time-ms: 86400000
  secret-key: NXRR+SVc/iI0UXHhZHOBMv92pTgFVHqPZoNlNV6onIo=
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc/swagger-ui.html
  paths-to-match: /input/**, /output/**, /servicio/**, /afiliado/**
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: reservation

server:
  servlet:
    context-path: /api/v1
  port: 8001